### ISSUE TITLE
missing file _respond.media.scss ?

### ISSUE THREAD

**Issue by FredericHeem** [stellar/solar#7]
Is the file  _respond.media.scss missing from the git repo ?

**Comment by irisli** [comment]
Seems like the file is in there. Where is the error being triggered for you?

Did you use npm to install solar? Solar is not up to date on npm.

**Comment by FredericHeem** [comment]
The file is probably on your local disk but not yet committed to git. Could you run the command `git status` and find out more about this file.
The package has been installed with the setup script provided by `interstellar-workspace`, not via `npm`

**Comment by bartekn** [comment]
This file seems to be commited: https://github.com/stellar/solar/blob/master/lib/_respond.media.scss
@FredericHeem, what error are you getting?

**Comment by FredericHeem** [comment]
```
frederic@frederic-VirtualBox:~/interstellar-workspace/interstellar-client$ interstellar develop
[17:16:09] Using gulpfile /usr/lib/node_modules/interstellar/gulpfile.js
[17:16:09] Starting 'serve-watch'...
[17:16:09] Starting 'clean'...
[17:16:09] Starting 'build:make-compiler'...
[17:16:09] Finished 'build:make-compiler' after 32 ms
[17:16:09] Finished 'clean' after 55 ms
[17:16:09] Starting 'build-watch'...
  ◠ Creating the chunk assets...   
/usr/lib/node_modules/interstellar/node_modules/node-sass/lib/index.js:409
  throw util._extend(new Error(), JSON.parse(result.error));
             ^
Error: file to import not found or unreadable: respond.media
Current dir: /home/frederic/interstellar-workspace/interstellar-client/node_modules/interstellar-core/node_modules/solar-css/styles/
    at Object.module.exports.renderSync (/usr/lib/node_modules/interstellar/node_modules/node-sass/lib/index.js:409:22)

```

**Comment by irisli** [comment]
Thanks for the report. I pushed a commit that should fix this error (https://github.com/stellar/solar/commit/a30cef6a5a2441dab51836cc0c360b9ee62c2c45).

I accidentally put the import statement in the `styles` folder instead of the `lib` folder where it was supposed to be.

**Comment by raybesiga** [comment]
@irisli I think there is still an issue with this. I have the exact same issue and I have the latest install from NPM. How do we fix it?

**Comment by irisli** [comment]
Hi. Sorry, this was my fault. The package on npm is often not up to date. I have pushed the changes to npm and you can now try again.

Alternatively, if you save your dependencies in your `package.json`, you can add the git repo as the source of the package (as opposed to npm) so that updates will pull from the updated Github repo. Here is an example of how that can be done.
```
  "dependencies": {
    "solar-css": "git+https://github.com/stellar/solar#master",
```

Let me know if you have any other issues.

**Comment by raybesiga** [comment]
Hi @irisli  Is there a way for updates from the Github to have continuous integration with the NPM package? I have tried again but get the following error after updating and running 'interstellar develop':

```javascript
[16:46:55] Using gulpfile ~/.npm_modules/lib/node_modules/interstellar/gulpfile.js
[16:46:55] Starting 'serve-watch'...
[16:46:55] Starting 'clean'...
[16:46:55] Starting 'build:make-compiler'...
[16:46:58] Finished 'build:make-compiler' after 2.95 s
[16:46:59] Finished 'clean' after 3.4 s
[16:46:59] Starting 'build-watch'...
  ◠ Creating the chunk assets...   
/Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/node-sass/lib/index.js:409
  throw util._extend(new Error(), JSON.parse(result.error));
             ^
Error: file to import not found or unreadable: solar/lib/index
Current dir: 
    at Object.module.exports.renderSync (/Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/node-sass/lib/index.js:409:22)
    at Tapable.<anonymous> (/Users/raybesiga/.npm_modules/lib/node_modules/interstellar/lib/webpack.compile-concat-plugin.es6:31:23)
    at Tapable.applyPluginsAsync (/Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Tapable.afterEmit (/Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/webpack/lib/Compiler.js:271:8)
    at Tapable.<anonymous> (/Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/webpack/lib/Compiler.js:266:14)
    at /Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/webpack/node_modules/async/lib/async.js:243:21)
    at /Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/gaze/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Users/raybesiga/.npm_modules/lib/node_modules/interstellar/node_modules/karma/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:42
```
Not sure what the issue is despite the update..

**Comment by irisli** [comment]
This is fixable by changing imports to references to solar from `solar` to `solar-css` in the `styles/main.header.scss` file.

From: 
```css
// solar-library-bundle
@import "solar/lib/index";
@import "solar-stellarorg/lib/index"; // uncomment to see how solar-stellarorg theme impacts the styles

// solar-css-bundle
@import "solar/styles/index";
@import "solar-stellarorg/styles/index"; // uncomment to see how solar-stellarorg theme impacts the styles
```

To:
```
// solar-library-bundle
@import "solar-css/lib/index";
@import "solar-stellarorg/lib/index"; // uncomment to see how solar-stellarorg theme impacts the styles

// solar-css-bundle
@import "solar-css/styles/index";
@import "solar-stellarorg/styles/index"; // uncomment to see how solar-stellarorg theme impacts the styles
```
